WIP: trying to access `mem` from the callback, but
this errors out:
```
error[E0524]: two closures require unique access to `mem` at the same time
```