WIP: try to pass `var` via `TryE`
but this fails mysteriously with:
```
Error: dependency cycle between modules in _build/default/ir_def:
   Rename
-> Construct
-> Construct
-> required by _build/default/ir_def/ir_def.cmxa
-> required by _build/default/exes/mo_ide.exe
```