Remove unused coverage report to fix spurious build errors (#1612)
nobody looked at it in a long time, and maybe bisect_ppx is responsible
for build errors like
```
    ocamldep exes/.didc.eobjs/didc.ml.d
File ".ppx/bef45e64034afd84ea3dacc05d4ff0e1/_ppx.ml", line 1:
Error: Files /nix/store/k0gr17yiypm51fcww5f0dsp3q8yssmds-ocaml4.08.1-bisect_ppx-1.4.0/lib/ocaml/4.08.1/site-lib/bisect_ppx/bisect_ppx.cmxa
       and /nix/store/2v1qbd3wxdj6869win87f837s7j0064v-ocaml-4.08.1/lib/ocaml/compiler-libs/ocamlcommon.cmxa
       make inconsistent assumptions over implementation Location
    ocamlopt mo_config/.mo_config.objs/native/mo_config__Flags.{cmx,o}
```
so remove this for now. We can resurrect it when we actually want to use
the coverage report.